# Generated by Django 3.0.6 on 2020-08-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compteur', '0002_auto_20200803_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteur',
            name='phase1_state',
            field=models.CharField(choices=[('OFF', 'Eteint'), ('ON', 'Allumé')], default='OFF', max_length=10),
        ),
        migrations.AddField(
            model_name='compteur',
            name='phase2_state',
            field=models.CharField(choices=[('OFF', 'Eteint'), ('ON', 'Allumé')], default='OFF', max_length=10),
        ),
        migrations.AddField(
            model_name='compteur',
            name='phase3_state',
            field=models.CharField(choices=[('OFF', 'Eteint'), ('ON', 'Allumé')], default='OFF', max_length=10),
        ),
    ]
