# Generated by Django 3.0.6 on 2020-08-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compteur', '0003_auto_20200803_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteur',
            name='modele',
            field=models.CharField(choices=[('Monophasé', 'Monophasé'), ('Biphasé', 'Biphasé'), ('Triphasé', 'Triphasé')], max_length=20),
        ),
    ]
