# Generated by Django 3.0.6 on 2020-07-08 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transformateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=45)),
                ('p_max', models.FloatField()),
                ('q_max', models.FloatField()),
                ('p_total', models.FloatField(default=0)),
                ('q_total', models.FloatField(default=0)),
                ('global_state', models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetailsTransfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant', models.DateTimeField(auto_now=True)),
                ('i_phase1', models.FloatField(default=0)),
                ('i_phase2', models.FloatField(default=0)),
                ('i_phase3', models.FloatField(default=0)),
                ('u_phase1', models.FloatField(default=0)),
                ('u_phase2', models.FloatField(default=0)),
                ('u_phase3', models.FloatField(default=0)),
                ('p_phase1', models.FloatField(default=0)),
                ('p_phase2', models.FloatField(default=0)),
                ('p_phase3', models.FloatField(default=0)),
                ('q_phase1', models.FloatField(default=0)),
                ('q_phase2', models.FloatField(default=0)),
                ('q_phase3', models.FloatField(default=0)),
                ('p_total', models.FloatField(default=0)),
                ('q_total', models.FloatField(default=0)),
                ('etat', models.CharField(max_length=45)),
                ('transformateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfos.Transformateur')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
