# Generated by Django 3.0.6 on 2020-06-04 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(default='RDC', max_length=45)),
                ('province', models.CharField(default='Haut-Katanga', max_length=45)),
                ('ville', models.CharField(default='Lubumbashi', max_length=45)),
                ('commune', models.CharField(max_length=45)),
                ('quartier', models.CharField(max_length=45)),
                ('avenue', models.CharField(max_length=45)),
                ('numero', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_adresse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.IntegerField(choices=[(0, 'CLASSE 1'), (1, 'CLASSE 2'), (3, 'CLASSE 3')])),
                ('p_max', models.FloatField()),
                ('q_max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.IntegerField(choices=[(0, 'Monophasé'), (1, 'Biphasé'), (2, 'Triphasé')])),
                ('credit', models.FloatField()),
                ('i_phase1', models.FloatField()),
                ('i_phase2', models.FloatField()),
                ('i_phase3', models.FloatField()),
                ('u_phase1', models.FloatField()),
                ('u_phase2', models.FloatField()),
                ('u_phase3', models.FloatField()),
                ('p_phase1', models.FloatField()),
                ('p_phase2', models.FloatField()),
                ('p_phase3', models.FloatField()),
                ('q_phase1', models.FloatField()),
                ('q_phase2', models.FloatField()),
                ('q_phase3', models.FloatField()),
                ('global_state', models.IntegerField(choices=[(0, 'OFF'), (1, 'ON')])),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Classes')),
                ('id_appart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Appartement')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45)),
                ('postnom', models.CharField(max_length=45)),
                ('prenom', models.CharField(max_length=45)),
                ('login', models.CharField(max_length=45)),
                ('psw', models.CharField(max_length=40)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Utilisateur')),
                ('email', models.CharField(max_length=45)),
            ],
            bases=('app.utilisateur',),
        ),
        migrations.CreateModel(
            name='TransfertCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now=True, verbose_name='Date et heure du transfert')),
                ('qteTransfert', models.FloatField()),
                ('idDest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destinataire', to='app.Compteur')),
                ('idExp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expediteur', to='app.Compteur')),
            ],
        ),
        migrations.CreateModel(
            name='Details_Compteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.FloatField()),
                ('instant', models.DateTimeField(auto_now=True)),
                ('i_phase1', models.FloatField()),
                ('i_phase2', models.FloatField()),
                ('i_phase3', models.FloatField()),
                ('u_phase1', models.FloatField()),
                ('u_phase2', models.FloatField()),
                ('u_phase3', models.FloatField()),
                ('p_phase1', models.FloatField()),
                ('p_phase2', models.FloatField()),
                ('p_phase3', models.FloatField()),
                ('q_phase1', models.FloatField()),
                ('q_phase2', models.FloatField()),
                ('q_phase3', models.FloatField()),
                ('etat', models.CharField(max_length=45)),
                ('id_compteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Compteur')),
            ],
        ),
        migrations.AddField(
            model_name='appartement',
            name='id_utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Utilisateur'),
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now=True, verbose_name="Date et heure de l'achat")),
                ('montant', models.FloatField()),
                ('qte_energie', models.FloatField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Classes')),
                ('id_compteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Compteur')),
            ],
        ),
    ]
