# Generated by Django 3.0.6 on 2020-06-13 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(default='RDC', max_length=45)),
                ('province', models.CharField(default='Haut-Katanga', max_length=45)),
                ('ville', models.CharField(default='Lubumbashi', max_length=45)),
                ('commune', models.CharField(max_length=45)),
                ('quartier', models.CharField(max_length=45)),
                ('avenue', models.CharField(max_length=45)),
                ('numero', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.IntegerField(choices=[(0, 'CLASSE 1'), (1, 'CLASSE 2'), (3, 'CLASSE 3')])),
                ('p_max', models.FloatField()),
                ('q_max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.IntegerField(choices=[(0, 'Monophasé'), (1, 'Biphasé'), (2, 'Triphasé')])),
                ('credit', models.FloatField()),
                ('active_class', models.IntegerField(choices=[(0, 'Domestique'), (1, 'Semi-industriel'), (2, 'Industriel')], default=0)),
                ('i_phase1', models.FloatField()),
                ('i_phase2', models.FloatField()),
                ('i_phase3', models.FloatField()),
                ('u_phase1', models.FloatField()),
                ('u_phase2', models.FloatField()),
                ('u_phase3', models.FloatField()),
                ('p_phase1', models.FloatField()),
                ('p_phase2', models.FloatField()),
                ('p_phase3', models.FloatField()),
                ('q_phase1', models.FloatField()),
                ('q_phase2', models.FloatField()),
                ('q_phase3', models.FloatField()),
                ('global_state', models.IntegerField(choices=[(0, 'OFF'), (1, 'ON')])),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Appartement')),
            ],
        ),
        migrations.CreateModel(
            name='Transformateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.CharField(max_length=45)),
                ('p_max', models.FloatField()),
                ('q_max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45)),
                ('postnom', models.CharField(max_length=45)),
                ('prenom', models.CharField(max_length=45)),
                ('psw', models.CharField(max_length=40)),
                ('telephone', models.CharField(max_length=20)),
                ('avatar', models.ImageField(default='medias/img/avatar.jpg', upload_to='medias/img/')),
            ],
        ),
        migrations.CreateModel(
            name='TransfertCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now=True, verbose_name='Date et heure du transfert')),
                ('qteTransfert', models.FloatField()),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destinataire', to='app.Compteur')),
                ('expeditaire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expediteur', to='app.Compteur')),
            ],
        ),
        migrations.CreateModel(
            name='Details_Compteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.FloatField()),
                ('instant', models.DateTimeField(auto_now=True)),
                ('i_phase1', models.FloatField()),
                ('i_phase2', models.FloatField()),
                ('i_phase3', models.FloatField()),
                ('u_phase1', models.FloatField()),
                ('u_phase2', models.FloatField()),
                ('u_phase3', models.FloatField()),
                ('p_phase1', models.FloatField()),
                ('p_phase2', models.FloatField()),
                ('p_phase3', models.FloatField()),
                ('q_phase1', models.FloatField()),
                ('q_phase2', models.FloatField()),
                ('q_phase3', models.FloatField()),
                ('etat', models.CharField(max_length=45)),
                ('compteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Compteur')),
            ],
        ),
        migrations.AddField(
            model_name='compteur',
            name='transformateur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Transformateur'),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance1', models.FloatField()),
                ('balance2', models.FloatField()),
                ('balance3', models.FloatField()),
                ('compteur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Compteur')),
            ],
        ),
        migrations.AddField(
            model_name='appartement',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Utilisateur'),
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now=True, verbose_name="Date et heure de l'Abonnement")),
                ('montant', models.FloatField()),
                ('qte_energie', models.FloatField()),
                ('etat', models.IntegerField(choices=[(0, 'En cours'), (1, 'Terminé')])),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Classes')),
                ('compteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Compteur')),
            ],
        ),
    ]
