# Generated by Django 3.0.6 on 2020-07-04 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='avenue',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='commune',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='quartier',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Appartement'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='avatar',
            field=models.ImageField(default='medias/img/user/avatar/avatar.jpg', unique=True, upload_to='img/user/avatar/'),
        ),
    ]
