# Generated by Django 3.0.6 on 2020-06-12 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_utilisateur_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.CharField(max_length=45)),
                ('p_max', models.FloatField()),
                ('q_max', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='achat',
            old_name='id_compteur',
            new_name='compteur',
        ),
        migrations.RenameField(
            model_name='appartement',
            old_name='id_adresse',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='appartement',
            old_name='id_utilisateur',
            new_name='utilisateur',
        ),
        migrations.RenameField(
            model_name='compteur',
            old_name='id_appart',
            new_name='appartement',
        ),
        migrations.RenameField(
            model_name='details_compteur',
            old_name='id_compteur',
            new_name='compteur',
        ),
        migrations.RenameField(
            model_name='transfertcredit',
            old_name='idDest',
            new_name='destinataire',
        ),
        migrations.RenameField(
            model_name='transfertcredit',
            old_name='idExp',
            new_name='expeditaire',
        ),
        migrations.AddField(
            model_name='compteur',
            name='transformateur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Transformateur'),
        ),
    ]
