# Generated by Django 3.0.6 on 2020-06-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200616_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transformateur',
            old_name='localisation',
            new_name='designation',
        ),
    ]
