# Generated by Django 3.0.6 on 2020-06-12 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200612_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now=True, verbose_name="Date et heure de l'Abonnement")),
                ('montant', models.FloatField()),
                ('qte_energie', models.FloatField()),
                ('etat', models.IntegerField(choices=[(0, 'En cours'), (1, 'Terminé')])),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Classes')),
            ],
        ),
        migrations.RemoveField(
            model_name='compteur',
            name='classe',
        ),
        migrations.DeleteModel(
            name='Achat',
        ),
        migrations.AddField(
            model_name='abonnement',
            name='compteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Compteur'),
        ),
    ]
