# Generated by Django 3.0.6 on 2020-06-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200616_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailscompteur',
            name='p_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='detailscompteur',
            name='q_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='detailstransfo',
            name='p_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='detailstransfo',
            name='q_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='compteur',
            name='global_state',
            field=models.IntegerField(choices=[(0, 'OFF'), (1, 'ON')], default=0),
        ),
    ]
