# Generated by Django 3.0.6 on 2020-06-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200620_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteur',
            name='p_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='compteur',
            name='q_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transformateur',
            name='p_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transformateur',
            name='q_total',
            field=models.FloatField(default=0),
        ),
    ]
