# Generated by Django 3.0.6 on 2020-06-12 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200613_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteur',
            name='transformateur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Transformateur'),
        ),
    ]
