# Generated by Django 3.0.6 on 2020-05-29 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransfertCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now=True, verbose_name='Date et heure du transfert')),
                ('qteTransfert', models.FloatField()),
                ('idDest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destinataire', to='app.Compteur')),
                ('idExp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expediteur', to='app.Compteur')),
            ],
        ),
    ]
