# Generated by Django 3.0.6 on 2020-08-03 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compteur', '0002_auto_20200803_1813'),
        ('achats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compteur.Classe'),
        ),
    ]
