# Generated by Django 3.0.6 on 2020-08-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_achat_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='prix',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='achat',
            name='quantite',
            field=models.FloatField(),
        ),
    ]
