# Generated by Django 3.0.6 on 2020-07-08 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45)),
                ('postnom', models.CharField(max_length=45)),
                ('prenom', models.CharField(max_length=45)),
                ('psw', models.CharField(max_length=40)),
                ('telephone', models.CharField(max_length=20)),
                ('avatar', models.ImageField(default='img/user/avatar/avatar.jpg', unique=True, upload_to='img/user/avatar/')),
            ],
        ),
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(default='RDC', max_length=45)),
                ('province', models.CharField(default='Haut-Katanga', max_length=45)),
                ('ville', models.CharField(default='Lubumbashi', max_length=45)),
                ('commune', models.CharField(max_length=45)),
                ('quartier', models.CharField(max_length=45)),
                ('avenue', models.CharField(max_length=45)),
                ('numero', models.PositiveIntegerField()),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Appartement')),
            ],
        ),
    ]
