# Generated by Django 3.0.6 on 2020-07-11 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='avenue',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='appartement',
            name='commune',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='appartement',
            name='numero',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appartement',
            name='pays',
            field=models.CharField(default='RDC', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='appartement',
            name='province',
            field=models.CharField(default='Haut-Katanga', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='appartement',
            name='quartier',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='appartement',
            name='ville',
            field=models.CharField(default='Lubumbashi', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Utilisateur'),
        ),
        migrations.DeleteModel(
            name='Adresse',
        ),
    ]
