# Generated by Django 3.0.6 on 2020-07-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseForfait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.IntegerField(choices=[(0, 'Classe 1'), (1, 'classe 2'), (2, 'classe 3')], default=0)),
                ('puissance_max', models.IntegerField(default=75)),
            ],
        ),
        migrations.CreateModel(
            name='ReglagesGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_par_watt', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Prix par watt')),
                ('alert_level', models.IntegerField(verbose_name="Niveau d'alerte minimal des transfos")),
            ],
        ),
    ]
